defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

#  =========== data-sets ===============

speech_type: librispeech  # librispeech/dns
noise_type: wham # wham / musan / dns

data_path : data/processed

# =============== DEBUG ===============
_d: False

# ================ DATA ======================

fs : 16000
 
window_size: 512  # FFT length
overlap: 0.5  # Overlap of STFT window
mode: train

# ================ CUDA ======================

device: cuda
gpus : -1

# ========= ModelCheckPoints =========

patience : 50
save_top_k: 5
save_last: True
ckpt_monitor: 'val_loss'

check_val_every_n_epoch : 1
precision : 16
progress_bar_refresh_rate : 5
log_gpu_memory : False
seed: 2036
eps: 1e-6
num_workers: 28
verbose: 1

# ======= Optimizer ===========

optimizer : Adam # Adam / sgd / AdamW
lr: 1e-4
epochs: 500
batch_size: 64
beta1: 0.9
beta2: 0.999
momentum: 0.9

# Hydra config
hydra:
  run:
    dir: models/${hydra.job.override_dirname}/
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test', 'dset.mix_json', 'dset.mix_dir',
          'num_prints', 'continue_from',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr
